active_site: spl
check_interval: 0.81s
check_window: 60s
max_workers: 2
mode: alert
months_to_check: 2
ntfy_topic: myappointments
pre_warm_offset: 30s
preferred_days: []
preferred_slug: ""
request_jitter: 0.18s
rest_cycle_checks: 12
rest_cycle_duration: 3s
scheduled_runs: []
strike_time: "09:00"
sites:
  spl:
    name: SPL
    baseurl: https://spl.libcal.com
    availabilityendpoint: /pass/availability/institution
    digital: true
    physical: false
    location: "0"
    bookinglinkselector: a.s-lc-pass-availability.s-lc-pass-digital.s-lc-pass-available
    loginform:
      usernamefield: username
      passwordfield: password
      submitbutton: submit
      csrfselector: ""
      username: ""
      password: ""
      email: ""
      authidselector: input[name="auth_id"]
      loginurlselector: input[name="login_url"]
    bookingform:
      actionurl: ""
      fields: []
      emailfield: email
    successindicator: Thank you!
    museums: {}
    preferredslug: ""
  kcls:
    name: KCLS
    baseurl: https://rooms.kcls.org
    availabilityendpoint: /pass/availability/institution
    digital: true
    physical: false
    location: "0"
    bookinglinkselector: a.s-lc-pass-availability.s-lc-pass-digital.s-lc-pass-available
    loginform:
      usernamefield: username
      passwordfield: password
      submitbutton: submit
      csrfselector: ""
      username: ""
      password: ""
      email: ""
      authidselector: input[name="auth_id"]
      loginurlselector: input[name="login_url"]
    bookingform:
      actionurl: ""
      fields: []
      emailfield: email
    successindicator: Thank you!
    museums: {}
    preferredslug: ""
